apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: shibuya
  name: shibuya
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shibuya
  template:
    metadata:
      labels:
        app: shibuya
    spec:
      serviceAccount: shibuya
      containers:
      - image: shibuya:local
        name: shibuya
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: shibuya
  name: shibuya
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: shibuya